In [1]:
import analysis
import numpy as np

In [18]:
dir = "..\\..\\corpus\\test_sample_1"
sr=48000
grain_duration = 0.1 # 100 ms
grain_size = int(grain_duration * sr)
analyzer = analysis.AnalyzerObject(dir,sr)
# df = analyzer.compute_grain_descriptors(grain_size)

In [ ]:
# analyzer.save_metadata(df, grain_duration)

Saved to csv to: ..\..\corpus\test_sample_1\metadata\grain_0.1_s_metadata_6d91620b.csv

In [12]:
metadata_path = "..\..\corpus\\test_sample_1\metadata\grain_0.1_s_metadata_6d91620b.csv"
df = analyzer.load_metadata(metadata_path)
_, df_scaled = analyzer.scale_metadata(df, 1) # PowerTransformer
df_scaled

,id,sr,index,size,centroid,flux,rolloff,flatness,spread,skewness,kurtosis,crest,rms
0,d30a270c1,48000,0,4800,-0.319778,10.193623,-0.332149,-0.187925,-0.308653,0.493483,0.669392,0.579800,0.713635
1,79eafff84,48000,4800,4800,-1.211254,9.507284,-1.786965,-1.256480,-1.656785,1.950264,2.496640,1.083543,2.546602
2,e8f352b2e,48000,9600,4800,-0.822939,0.965473,-1.011879,-0.821342,-0.938661,0.952537,1.056003,1.192107,1.535128
3,8641ab0e4,48000,14400,4800,-0.138806,0.365019,-0.084830,-0.281145,-0.310438,0.160546,0.174365,0.286398,0.439172
4,4494c3159,48000,19200,4800,0.079214,0.085175,0.001713,-0.248912,-0.309645,0.030725,0.062472,0.714712,0.542749
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,249facc45,48000,456000,4800,1.869598,-0.449237,0.899280,1.429923,1.162446,-1.312439,-0.975241,-0.120887,-0.404557
96,7f47810f9,48000,460800,4800,1.043972,-0.409448,0.709996,1.005246,0.820181,-0.785600,-0.642386,-0.222641,-0.425712
97,cf1da826d,48000,465600,4800,0.611577,-0.284441,0.267012,0.599005,0.252752,-0.250918,-0.216306,-0.399408,-0.477217
98,46efe1639,48000,470400,4800,0.270090,-0.199774,-0.028227,0.338247,0.107855,0.006269,-0.001508,-0.303282,-0.400492
99,1268d81c2,48000,475200,4800,0.185784,-0.362130,-0.119756,0.257017,0.072816,-0.019387,-0.007733,-0.168047,-0.370070

In [21]:
descriptor_list = ["centroid", "flux", "rolloff", "flatness", "spread", "skewness", "kurtosis", "crest", "rms"]
df_scaled[descriptor_list]

,centroid,flux,rolloff,flatness,spread,skewness,kurtosis,crest,rms
0,-0.319778,10.193623,-0.332149,-0.187925,-0.308653,0.493483,0.669392,0.579800,0.713635
1,-1.211254,9.507284,-1.786965,-1.256480,-1.656785,1.950264,2.496640,1.083543,2.546602
2,-0.822939,0.965473,-1.011879,-0.821342,-0.938661,0.952537,1.056003,1.192107,1.535128
3,-0.138806,0.365019,-0.084830,-0.281145,-0.310438,0.160546,0.174365,0.286398,0.439172
4,0.079214,0.085175,0.001713,-0.248912,-0.309645,0.030725,0.062472,0.714712,0.542749
...,...,...,...,...,...,...,...,...,...
95,1.869598,-0.449237,0.899280,1.429923,1.162446,-1.312439,-0.975241,-0.120887,-0.404557
96,1.043972,-0.409448,0.709996,1.005246,0.820181,-0.785600,-0.642386,-0.222641,-0.425712
97,0.611577,-0.284441,0.267012,0.599005,0.252752,-0.250918,-0.216306,-0.399408,-0.477217
98,0.270090,-0.199774,-0.028227,0.338247,0.107855,0.006269,-0.001508,-0.303282,-0.400492
99,0.185784,-0.362130,-0.119756,0.257017,0.072816,-0.019387,-0.007733,-0.168047,-0.370070

In [28]:
descriptor_list = ["centroid", "flux", "rolloff", "flatness", "spread", "skewness", "kurtosis", "crest", "rms"]

grain_ana.plot_flexible_histograms(df_scaled, descriptor_list, grain_duration)

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set a consistent aesthetic style
sns.set_theme(style="whitegrid")

def plot_flexible_histograms(df, n_cols=3, color='steelblue', n_bins=30):
    """
    Plots histograms for all columns in a DataFrame into a grid with a fixed number of columns.
    - df: pandas DataFrame containing the scaled features
    - n_cols: int, number of columns in the subplot grid
    - color: str, color for all histograms
    - bins: int, number of bins for the histograms
    """
    
    df = df.iloc[:, 4:] # consider only descriptors
    feature_names = df.columns
    n_features = len(feature_names)
    n_rows = np.ceil(n_features / n_cols)
    
    fig, axes = plt.subplots(
        n_rows, 
        n_cols, 
        figsize=(n_cols * 4, n_rows * 3.5), 
        sharex=False, 
        sharey=False
    )
    axes_flat = axes.flatten()
    
    for i, col in enumerate(feature_names):
        sns.histplot(
            data=df, 
            x=col, 
            kde=False, # True for a fitted line     
            ax=axes_flat[i], 
            color=color,     
            bins=n_bins
        )
        axes_flat[i].set_title(f'{col}'.capitalize() + 'Distribution', fontsize=11, fontweight='bold')
        # axes_flat[i].set_xlabel('Scaled Value')
        # axes_flat[i].set_ylabel('Count')

    # If the number of features doesn't perfectly fill the last row, delete the empty axes
    for j in range(i + 1, len(axes_flat)):
        fig.delaxes(axes_flat[j])
        
    plt.tight_layout()
    plt.savefig('features_histograms.png', dpi=300, bbox_inches='tight')

descriptor_list = ["centroid", "flux", "rolloff", "flatness", "spread", "skewness", "kurtosis", "crest", "rms"]

plot_flexible_histograms(df_scaled[descriptor_list], n_cols=3, color='indigo')

Index(['centroid', 'flux', 'rolloff', 'flatness', 'spread', 'skewness',
       'kurtosis', 'crest', 'rms'],
      dtype='object')

KeyboardInterrupt: